Complex Puzzle
ChaseBENNC9/GameJam-Charika pull request #36
Opened 2024-03-20 21:32 UTC by ChaseBENNC9

This will expand upon the interactions feature by allowing a scenario where the player needs to collect multiple items before they can actually use this. 
The most basic form is a door that requires two keys and a more complex idea is to be attaching objects together to reach something or to build a tool to help the player

2024-03-26 01:14 UTC, ChaseBENNC9 commented
The system for how the goal works when it has the correct items has been refactored.
I am now using the unity events which allows me to choose a method in the inspector that will be called.
this is a much cleaner process and means i dont need an endless if else check for each type of puzzle we have

2024-03-27 21:51 UTC, ChaseBENNC9 commented
- I have refactored alot of the code so the goal is split into two classes.  
Item goal as the parent and Complex goal as a child which has changed certain methods to fit the behaviour needed

2024-03-27 22:55 UTC, erokasyuart requested changes
I have no issue with the code other than the debug logs and general housekeeping.

2024-03-27 22:55 UTC, erokasyuart commented on AI Game Jam/Assets/Scripts/ItemGoal.cs
> +
Too much whitespace

2024-03-27 22:55 UTC, erokasyuart commented on AI Game Jam/Assets/Scripts/ItemGoal.cs
> +        Debug.Log("Wheel turned and water drained");
All the debug logs must go!!

2024-03-27 22:55 UTC, erokasyuart commented on AI Game Jam/Assets/Scripts/PlayerInteraction.cs
> +                other
This is weird indentation...

2024-03-27 23:15 UTC, erokasyuart approved these changes

2024-03-27 23:16 UTC, merged